apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: front
  name: front
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  - name: "110"
    port: 110
    targetPort: 110
  - name: "143"
    port: 143
    targetPort: 143
  - name: "993"
    port: 993
    targetPort: 993
  - name: "995"
    port: 995
    targetPort: 995
  - name: "25"
    port: 25
    targetPort: 25
  - name: "465"
    port: 465
    targetPort: 465
  - name: "587"
    port: 587
    targetPort: 587
  selector:
    io.kompose.service: front
status:
  loadBalancer: {}
