apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: front
    spec:
      containers:
      - env:
        - name: ADMIN
        - name: ANTIVIRUS
        - name: AUTH_RATELIMIT
        - name: BIND_ADDRESS4
        - name: BIND_ADDRESS6
        - name: COMPOSE_PROJECT_NAME
        - name: DISABLE_STATISTICS
        - name: DMARC_RUA
        - name: DMARC_RUF
        - name: DOMAIN
        - name: FETCHMAIL_DELAY
        - name: HOSTNAMES
        - name: MESSAGE_SIZE_LIMIT
        - name: PASSWORD_SCHEME
        - name: POSTMASTER
        - name: RECIPIENT_DELIMITER
        - name: RELAYHOST
        - name: RELAYNETS
        - name: ROOT
        - name: SECRET_KEY
        - name: SITENAME
        - name: TLS_FLAVOR
        - name: VERSION
        - name: WEBDAV
        - name: WEBMAIL
        - name: WEBSITE
        - name: WEB_ADMIN
        - name: WEB_WEBMAIL
        - name: WELCOME
        - name: WELCOME_BODY
        - name: WELCOME_SUBJECT
        image: 'mailu/nginx:'
        name: front
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 110
        - containerPort: 143
        - containerPort: 993
        - containerPort: 995
        - containerPort: 25
        - containerPort: 465
        - containerPort: 587
        resources: {}
        volumeMounts:
        - mountPath: /certs
          name: front-claim0
      restartPolicy: Always
      volumes:
      - name: front-claim0
        persistentVolumeClaim:
          claimName: front-claim0
status: {}
