apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --file docker-compose.sample.yml
    kompose.version: 1.1.0 (36652f6)
    traefik.docker.network: http_network
    traefik.enable: "true"
    traefik.frontend.rule: Host:spam.
    traefik.port: "11334"
  creationTimestamp: null
  labels:
    io.kompose.service: mailserver
  name: mailserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mailserver
    spec:
      containers:
      - env:
        - name: DBPASS
        - name: RSPAMD_PASSWORD
        image: 'hardware/mailserver:'
        name: mailserver
        ports:
        - containerPort: 25
        - containerPort: 143
        - containerPort: 587
        - containerPort: 993
        - containerPort: 4190
        resources: {}
        volumeMounts:
        - mountPath: /var/mail
          name: mailserver-claim0
      restartPolicy: Always
      volumes:
      - name: mailserver-claim0
        persistentVolumeClaim:
          claimName: mailserver-claim0
status: {}
