apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c --file docker-compose.sample.yml
    kompose.version: 1.1.0 (36652f6)
    traefik.docker.network: http_network
    traefik.enable: "true"
    traefik.frontend.rule: Host:postfixadmin.
    traefik.port: "8888"
  creationTimestamp: null
  labels:
    io.kompose.service: postfixadmin
  name: postfixadmin
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: postfixadmin
status:
  loadBalancer: {}
